name: webview_flutter_example
description: Demonstrates how to use the webview_flutter plugin.

version: 1.0.4

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  e2e: "^0.7.0+1"

flutter:
  uses-material-design: true
  assets:
    - assets/sample_audio.ogg
